
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [opened, edited, milestoned]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign milestoned to Project
    steps:
    - name: Assign issues and pull requests with milestones to project
      uses: elastic/assign-one-project-github-action@1.2.1
      if: github.event.issue && github.event.issue.milestone
      with:
        project: 'https://github.com/orgs/WertTest/projects/1'
        project_id: '5875539'
        column_name: 'Backlog'
    - name: Assign issues and pull requests with milestones to project
      uses: elastic/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' && github.event.pull_request
      with:
        project: 'https://github.com/orgs/WertTest/projects/1'
        project_id: '5875539'
        column_name: 'Ready'