name: "Testing"
on:
  issues:
    types: [labeled]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://env4h2kq1w4u.x.pipedream.net/${{ github.event.issue.number }}/${{ github.event.label.name }}?repo=${{ github.event.issue.url }}"
        method: 'POST'
        username: 'testuser'
        password: 'testpw'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
