name: "Testing"
on:
  issues:
    types: [labeled]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://env4h2kq1w4u.x.pipedream.net/"
        method: 'POST'
        username: 'test'
        password: ${{ secrets.HTTP_TEST_TOKEN }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"url": "${{ github.event.issue.url }}", "label": "${{ github.event.label.name }}"}'
