name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    typed: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: AlexanderWert/issue-labeler@v2.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml        
        enable-versioned-regex: 0
    - uses: AlexanderWert/get-user-teams-membership@v1.0.4
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: 'secondteam'
        usernamesToExclude: |
          abc
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    - name: Show Outputs
      run: |
        echo "::debug::isTeamMember: ${{ steps.checkUserMember.outputs.isTeamMember }}"
        echo "::debug::isExcluded: ${{ steps.checkUserMember.outputs.isExcluded }}"
    - if: steps.checkUserMember.outputs.isTeamMember != 'true' && steps.checkUserMember.outputs.isExcluded != 'true'
      uses: AlexanderWert/issue-labeler@v2.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/team-labeler.yml
        enable-versioned-regex: 0
