name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    typed: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: AlexanderWert/issue-labeler@v2.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
