name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    typed: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: AlexanderWert/issue-labeler@v2.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml        
        enable-versioned-regex: 0
    - uses: AlexanderWert/get-user-teams-membership@v1
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: 'customteam'
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    - if: ${{ !steps.checkUserMember.outputs.isTeamMember }}
      uses: AlexanderWert/issue-labeler@v2.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/team-labeler.yml
        enable-versioned-regex: 0
