name: "Regex Tester"
on:
  issues:
    types: [labeled]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: regex
        with:
          result-encoding: string
          script: |
            console.log(context);
            const urgencyLabel = context.label.name;
            return urgencyLabel ?? "";
      - name: Show export
        run: echo "${{ steps.regex.outputs.result }}"
