name: "Regex Tester"
on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: regex
        with:
          github-token: ${{ secrets.MY_PAT }}
          result-encoding: string
          script: |
            const urgencyLabel = context.issue.labels.map(l => l.name).find(name => name.startsWith('urgency:'));
            return urgencyLabel ?? "";
      - name: Show export
        run: echo "${{ steps.regex.outputs.result }}"
