name: Card moved

on:
  pull_request:
    types:
      - closed

jobs:
  check_is_otel:
    name: Check is OTel
    runs-on: ubuntu-latest
    outputs:
      is_otel: ${{ steps.otel.outputs.capturedContent == 'xyz' }}
    steps:
    - name: Is OTel
      id: otel
      uses: AlexanderWert/github-extract-content-from-pr-diff@main
      with:
        github-token: ${{github.token}}
        pathToScan: "articles"
        newFilesOnly: true
        regex: '^\+\s+-\s?slug:\s*"?(xyz)"?\s*$'
  add_to_project:
    name: Run job
    runs-on: ubuntu-latest
    needs: check_is_otel
    if: needs.check_is_otel.outputs.is_otel == 'true'
    steps:
    - name: Extract slug
      id: slug
      uses: AlexanderWert/github-extract-content-from-pr-diff@main
      with:
        github-token: ${{github.token}}
        pathToScan: "articles"
        newFilesOnly: true
        regex: '^\+slug:\s*"?([\w-]+)"?\s*$'
    - name: Show Slug
      run: echo "The slug is - ${{ steps.slug.outputs.capturedContent }}"
