name: "Testing"
on:
  issues:
    types: [opened]

jobs:
  blub:
    runs-on: ubuntu-latest
    steps:
    - name: Show issue
      run: |
        echo "${{ JSON.stringify(github.event.issue.title) }}"
    - name: Show Body
      run: |
        echo "${{ JSON.stringify(github.event.issue.body) }}"
