name: Card moved

on:
  project_card:
    types:
      - moved

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
    - name: Show data
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      #run: echo "${{ fromJson(steps.config.outputs.content).persons[steps.pagerduty.outputs.person_id].name }}"      
      run: |
        echo "$GITHUB_CONTEXT"
