name: Card moved

on:
  pull_request:
    types:
      - closed

jobs:
  add-to-project:
    name: PR closed
    runs-on: ubuntu-latest
    steps:
    - name: Show data
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      #run: echo "${{ fromJson(steps.config.outputs.content).persons[steps.pagerduty.outputs.person_id].name }}"      
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Extract slug
      uses: AlexanderWert/github-extract-content-from-pr-diff@main
      with:
        github-token: ${{github.token}}
        pathToScan: "articles"
        newFilesOnly: true
        regex: '^\+slug: "(.*)"$'
